site:
  title: Testify Documentation
  start_page: mainComponent::index.adoc
content:
  sources:
  - url: https://github.com/Testibus-Team4/yoko.git
    branches: HEAD
    start_path: docs/mainComponent
ui:
  supplemental_files: ./supplemental-ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true