# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload test reports
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: reports
        path: '*/build/reports'
    - name: Upload xml test results
      if: always()   # make sure we run it every time even if test step fails
      uses: actions/upload-artifact@v3.1.0
      with:
          name: xml-report
          path: "**/test-results/**/*.xml"
    - name: Upload test results to Test-hub.io
      if: always()   # make sure we run it every time even if test step fails
      uses: testhub-io/testhub-io.action@v0.62
      with:
        test_result_pattern: "**/test-results/**/*.xml"
    - name: Link to Test-hub.io
      if: always()
      run: echo "https://test-hub.io/OpenLiberty/projects/yoko/runs/$GITHUB_RUN_NUMBER"


